### PR TITLE
Flag coterminous places

### PR DESCRIPTION
**Pull request by stepps00**
Fixes a portion of whosonfirst-data/whosonfirst-data#1906.

This PR attempts flag any locality, localadmin, county, macrocounty, or region record as coterminous with any parent records that are similar in size and have similar names. 

The script I used to find these coterminous records essentially compares the `geom:size` and name (`wof:name`, unless `name:eng_x_preferred` is available) of each record to the same size and name of each record in it's hierarchy. If the matching distance is within two characters and the geom size of the record is within 15% the geom size of the parent record, the records were considered "coterminous". There are likely edge cases I'm not considering here, but this did seem to find all cases in this repo (and others) that I expected.

This should not involve any PIP work, we should be able to merge once approved.

### CODE REVIEW

**Review by nvkelso — APPROVED** [review]
These all look good.

It looks like there could be _even more_ marked coterminous? When verifying some of the smaller "towns" in this PR I found this [Wikipedia table](https://en.wikipedia.org/wiki/Equivalent_territory).

**Comment by stepps00** [comment]
A mixed bag, but here are notes for each locality listed on that page:

name | note
-- | --
Québec | 101737491 and 890458033 were not matched because the size difference between the two geometries was too large
Montréal | 101736545 and 890458661 were not matched because the size difference between the two geometries was too large
Shawinigan | flagged in PR
La Tuque | flagged in PR
Sherbrooke | flagged in PR
Gatineau | flagged in PR
Rouyn-Noranda | flagged in PR
Mirabel | flagged in PR
Jamésie | not an admin place from statscan (Northern Quebec)
Kativik | not an admin place from statscan (Northern Quebec)
Eeyou Istchee | not an admin place from statscan (Northern Quebec)
Les Îles-de-la-Madeleine | 890457171 is not coterminous with any of it's parents or descendants
Longueuil | 101738793 is not coterminous with any of it's parents or descendants
Trois-Rivières | 101738021 is not coterminous with any of it's parents or descendants
Saguenay | 101737173 is not coterminous with any of it's parents or descendants
Lévis | 101737987 and 890458877 should be flagged, but were not
Laval | 101737759 and 890457693 should be flagged, but were not

I'm going to re-evaluate the way I'm comparing geometries to fix the Levis and Laval examples.

The Montreal and Quebec could also be caught, but the geom difference inn these cases is actually quite large. Because of the large geom diff, I may need to flag these by hand using the `wof:capital` and `wof:capital_of` properties.

**Comment by stepps00** [comment]
I tweaked the logic in my script to better compare geometry sizes, the results are in 713af5e. This caught Québec, Lévis, and Laval as coterminous with a parent record. The only coterminous link that wasn't caught in records for Montréal.

**Locality**: https://spelunker.whosonfirst.org/id/101736545/
**County**: https://spelunker.whosonfirst.org/id/890458661/

While these places should be marked as coterminous, I think it's best that these were not caught as part of this crawl script because the geometries of these two places is quite large. I'll manually adjust these two records, then this PR should be ready for merge.

**Comment by nvkelso** [comment]
LGTM, thanks!

**Pull request merged**
